// Generated by ReScript, PLEASE EDIT WITH CARE


var NativeBaseProvider = {};

var Container = {};

var HStack = {};

var VStack = {};

var Center = {};

export {
  NativeBaseProvider ,
  Container ,
  HStack ,
  VStack ,
  Center ,
  
}
/* No side effect */
