// Generated by ReScript, PLEASE EDIT WITH CARE


var NativeBaseProvider = {};

var Container = {};

var HStack = {};

var VStack = {};

var Center = {};

var $$Text = {};

var Button = {};

var ScrollView = {};

var Item = {};

var List = {
  Item: Item
};

export {
  NativeBaseProvider ,
  Container ,
  HStack ,
  VStack ,
  Center ,
  $$Text ,
  Button ,
  ScrollView ,
  List ,
  
}
/* No side effect */
