// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "bs-platform/lib/es6/belt_Int.js";
import * as AppContext from "../AppContext.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      sectionContainer: {
        marginTop: 32,
        paddingHorizontal: 24
      },
      sectionTitle: {
        fontSize: 24,
        fontWeight: "600"
      },
      sectionDescription: {
        fontSize: 18,
        fontWeight: "400",
        marginTop: 8
      },
      highlight: {
        fontWeight: "700"
      }
    });

function Home(Props) {
  var context = React.useContext(AppContext.context);
  var text = context.text;
  var setText = context.setText;
  var charges = context.charges;
  var setCharges = context.setCharges;
  var chargesList = Belt_Array.mapWithIndex(charges, (function (i, charge) {
          return React.createElement(ReactNative.Text, {
                      children: String(charge),
                      key: String(i)
                    });
        }));
  var buttonPressed = function (_input) {
    if (text === "") {
      return ;
    }
    var val = Belt_Int.fromString(text);
    if (val !== undefined) {
      return Curry._1(setCharges, (function (prev) {
                    return prev.concat([val]);
                  }));
    } else {
      console.log("Enter a numerical value");
      return ;
    }
  };
  var onChangeText = function (input) {
    return Curry._1(setText, (function (_prev) {
                  return input;
                }));
  };
  var sumArray = function (array) {
    return Belt_Array.reduce(array, 0, (function (acc, item) {
                  return acc + item | 0;
                }));
  };
  return React.createElement(ReactNative.SafeAreaView, {
              children: null
            }, React.createElement(ReactNative.View, {
                  style: styles.sectionContainer,
                  children: null
                }, React.createElement(ReactNative.Button, {
                      onPress: buttonPressed,
                      title: "Charge"
                    }), React.createElement(ReactNative.TextInput, {
                      keyboardType: "numeric",
                      onChangeText: onChangeText,
                      onSubmitEditing: buttonPressed,
                      placeholder: "placeholder text",
                      value: text
                    }), React.createElement(ReactNative.View, {
                      style: styles.sectionContainer,
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "Charges:"
                        }), React.createElement(ReactNative.ScrollView, {
                          children: chargesList
                        }))), React.createElement(ReactNative.View, {
                  style: styles.sectionContainer,
                  children: null
                }, React.createElement(ReactNative.Text, {
                      children: "Total: "
                    }), React.createElement(ReactNative.Text, {
                      children: String(sumArray(charges))
                    })));
}

var make = Home;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
