// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

function Items$Items(Props) {
  return React.createElement(ReactNative.Text, {
              children: "Hello from Items"
            });
}

var Items = {
  make: Items$Items
};

export {
  Items ,
  
}
/* react Not a pure module */
