// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var settings_charges = [];

function settings_setCharges(param) {
  
}

var settings = {
  charges: settings_charges,
  setCharges: settings_setCharges
};

var context = React.createContext(settings);

var provider = context.Provider;

function AppContext$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: AppContext$Provider
};

export {
  settings ,
  context ,
  Provider ,
  
}
/* context Not a pure module */
